import { BaseColors } from './colors'
import type { Theme } from './types'

export const DarkTheme: Theme = {
  mode: 'dark',
  colors: {
    background: BaseColors.backgroundDark,
    surface: BaseColors.surfaceDark,
    primary: BaseColors.primary,
    primaryDark: BaseColors.primaryDark,
    heroCard: BaseColors.heroCard,
    primaryBackground: BaseColors.primaryDarkBackground,
    accent: BaseColors.accent,
    accentBackground: BaseColors.accentDarkBackground,
    accentDark: BaseColors.accentDark,
    aiInsightBackground: BaseColors.accentDarkBackground,
    success: BaseColors.success,
    successBackground: BaseColors.successDarkBackground,
    warning: BaseColors.warning,
    danger: BaseColors.danger,
    dangerBackground: BaseColors.dangerLight,
    dangerTint: BaseColors.dangerTint,
    storyCardInner: BaseColors.storyCardInner,
    storyGreen: BaseColors.storyGreen,
    storyPurple: BaseColors.storyPurple,
    storyLightPurple: BaseColors.storyLightPurple,
    storyBlack: BaseColors.storyBlack,
    chatBubbleBorder: BaseColors.chatBubbleBorderDark,
    chartMuted: BaseColors.chartMutedDark,
    textPrimary: BaseColors.textPrimaryDark,
    textSecondary: BaseColors.textSecondaryDark,
    textTertiary: BaseColors.textTertiaryDark,
    border: BaseColors.borderDark,
    shadow: BaseColors.shadowDark,
    shadowColor: BaseColors.shadowColorDark,
    socialApple: BaseColors.socialAppleDark,
    googleBlue: BaseColors.googleBlue,
    googleRed: BaseColors.googleRed,
    googleYellow: BaseColors.googleYellow,
    googleGreen: BaseColors.googleGreen,
  },
}
